### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by odirjar** [crate-crypto/go-ipa#34]
It looks like this has been pulled in by some open source projects, but since this project has no license, they are not authorized to use or distribute this code. Would you please consider adding a license to this project?

This discusses the challenges with not providing a license:
https://choosealicense.com/no-permission/

**Comment by kevaundray** [comment]
Hey, thanks for opening this. I have added an APACHE license to the project. 

Let me know if you also need an MIT License

**Comment by kevaundray** [comment]
Have added both licenses, so closing the issue!
