### ISSUE TITLE
Function description mismatch in element.go

### ISSUE THREAD

**Issue by gabrocheleau** [crate-crypto/go-ipa#65]
It seems like the normalize method has the wrong description (the comment describes a function called `IsIdentity`): https://github.com/crate-crypto/go-ipa/blob/master/banderwagon/element.go#L373

**Comment by jsign** [comment]
Thank you for the report!
I'll fix it in one of the open PRs that I've in the pipeline :)

**Comment by jsign** [comment]
Fixed in https://github.com/crate-crypto/go-ipa/pull/63
